"""Regenerate kalaignar/pose_data.py from the game's pose source of truth.

The game repo's tools/generate_placeholder_sprites.py defines every fighter's
per-frame poses, tuned against real gameplay hitboxes. This script imports it
and emits a static pose_data.py so Kalaignar needs no game checkout at runtime
but never hand-maintains poses.

Run after the game's pose sets change:
    python tools/sync_poses.py [--game "C:/Workspace/Warriors art"]
"""

import argparse
import importlib.util
from pathlib import Path

## Game generator function -> Kalaignar character id.
CHARACTERS = {
    "lathiyal_animations": "bengal_lathi",
    "musti_animations": "varanasi_musti",
    "silambar_animations": "tamilnadu_silambam",
    "gatka_animations": "punjab_gatka",
    "kalari_animations": "kerala_kalari",
    "thangta_animations": "manipur_thangta",
    "mardani_animations": "maharashtra_mardani",
    "parikhanda_animations": "bihar_parikhanda",
}

## Animations that repeat while their state holds (matches the game's importer).
LOOPING = {"idle", "walk", "crouch", "jump"}

## Pose keys the puppet renderer understands; everything else (shield flags,
## whip curvature, …) is a stick-generator detail the ARTIST's drawing covers.
SUPPORTED_KEYS = {
    "hip_y", "lean", "front_arm", "rear_arm", "front_foot", "rear_foot",
    "staff_angle", "staff_offset", "staff_len", "lying",
}


def load_game_generator(game_dir: Path):
    src = game_dir / "tools" / "generate_placeholder_sprites.py"
    if not src.exists():
        raise SystemExit(f"game generator not found: {src}")
    spec = importlib.util.spec_from_file_location("wa_sprites", src)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def convert(anims: dict) -> dict:
    out = {}
    for name, (fps, poses) in anims.items():
        clean = [
            {k: v for k, v in pose.items() if k in SUPPORTED_KEYS} for pose in poses
        ]
        out[name] = (fps, name in LOOPING, clean)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game", type=Path, default=Path("C:/Workspace/Warriors art"))
    args = parser.parse_args()

    module = load_game_generator(args.game)
    data = {}
    for func_name, character in CHARACTERS.items():
        fn = getattr(module, func_name, None)
        if fn is None:
            print(f"  skip {character}: {func_name} not in game generator")
            continue
        data[character] = convert(fn())
        print(f"  {character}: {len(data[character])} animations")

    out = Path(__file__).resolve().parent.parent / "kalaignar" / "pose_data.py"
    with out.open("w", encoding="utf-8", newline="\n") as f:
        f.write('"""GENERATED by tools/sync_poses.py — do not edit by hand.\n\n')
        f.write("Source of truth: the game repo's tools/generate_placeholder_sprites.py.\n")
        f.write('Format: character -> {anim: (fps, loop, [pose dicts])}."""\n\n')
        f.write("CHARACTER_POSES = ")
        f.write(repr(data))
        f.write("\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
